#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

# Not saved by default
ynh_app_setting_set --key=garmin_password --value="$garmin_password"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd "$install_dir"
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade --index-url https://git.dryusdan.fr/api/packages/Dryusdan/pypi/simple/ --extra-index-url https://pypi.python.org/simple garmin-to-fittrackee=="$(ynh_app_upstream_version)"

    ynh_safe_rm "$install_dir/.cache/pip"
popd

#=================================================
# INITIALIZE DATABASE
#=================================================
ynh_script_progression "Initializing database..."

set -a

ynh_hide_warnings env HOME="$install_dir" "$install_dir"/venv/bin/garmin2fittrackee setup config-tool --database-path "$install_dir"

set +a

#=================================================
# ADD A CRON JOB
#=================================================
ynh_config_add --template="garmin-to-fittrackee.cron" --destination="/etc/cron.d/$app"

chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_logrotate
touch "/var/log/$app/$app.log"
chown "$app":"$app" "/var/log/$app/$app.log"

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add $app --description="$app service" --log "/var/log/$app/$app.log"

# Configure the systemd timer
ynh_config_add --template="systemd.timer" --destination="/etc/systemd/system/$app.timer"
systemctl enable $app.timer --quiet
systemctl start $app.timer

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
