#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."


if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

systemctl stop $app.timer
systemctl disable $app.timer --quiet
ynh_config_remove_systemd
ynh_safe_rm "/etc/systemd/system/$app.timer"

ynh_config_remove_logrotate

if ynh_app_upgrading_from_version_before 0.8.4~ynh2
then
ynh_safe_rm "/etc/cron.d/$app"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
