#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app":"$app" "$install_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/etc/systemd/system/${app}.service"
systemctl enable "${app}.service" --quiet
yunohost service add $app --description="$app service" --log "/var/log/$app/$app.log"

ynh_restore "/etc/systemd/system/$app.timer"
systemctl enable $app.timer --quiet
systemctl start $app.timer


#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/etc/cron.d/$app"

ynh_restore "/var/log/$app/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
